command:
  # The permission of the command "/hub"
  name: "hub"
  # The aliases of the command (set to empty for no permission)
  permission: ""
  # The name of the server of the command
  aliases: ["lobby", "l"]
  # The message it should send you to
  hub-server-name: "hub"
  # The name sent to the player upon executing the command
  message: "&eYou are now being sent to <hub_name>..."

# THERE IS NO CONFIG
# This file is acutally not even used yo
